# VERSION               0.0.2
# DOCKER-VERSION        0.4.0
#
from    base:ubuntu-12.10
maintainer  Thomas Frössman <thomasf@josysstem.se>
add sources.list /etc/apt/sources.list
run DEBIAN_FRONTEND=noninteractive apt-get update
# run DEBIAN_FRONTEND=noninteractive apt-get install -y -q && apt-get clean
expose  80 443
# cmd ["/usr/local/bin/app", "run"]
